import * as SQLite from 'expo-sqlite';


const db = SQLite.openDatabaseSync("finansel.db")


export const createDatabase = ()=>{
      const statements = [
        `CREATE TABLE IF NOT EXISTS INCOME_CATEGORY (
            ID INTEGER PRIMARY KEY AUTOINCREMENT,
            NAME TEXT NOT NULL,
            IS_INVESTABLE INTEGER NOT NULL DEFAULT 0
        );`,
        `CREATE TABLE IF NOT EXISTS INCOME_PERIOD (
            ID INTEGER PRIMARY KEY AUTOINCREMENT,
            NAME TEXT NOT NULL,
            TOTAL_INCOME REAL NOT NULL,
            BUDGETED_AMOUNT REAL,
            START_DATE TEXT NOT NULL,
            END_DATE TEXT NOT NULL,
            INCOME_CATEGORY_ID INTEGER,
            FOREIGN KEY (INCOME_CATEGORY_ID) REFERENCES INCOME_CATEGORIES (ID)
        );`,
        `CREATE TABLE IF NOT EXISTS SUB_PERIODS (
            ID INTEGER PRIMARY KEY AUTOINCREMENT,
            NAME TEXT NOT NULL,
            BUDGETED_AMOUNT REAL NOT NULL,
            START_DATE TEXT NOT NULL,
            END_DATE TEXT NOT NULL,
            INCOME_PERIOD_ID INTEGER NOT NULL,
            FOREIGN KEY (INCOME_PERIOD_ID) REFERENCES INCOME_PERIODS (ID) ON DELETE CASCADE
        );`,
        `CREATE TABLE IF NOT EXISTS TRANSACTIONS (
            ID INTEGER PRIMARY KEY AUTOINCREMENT,
            AMOUNT REAL NOT NULL,
            DESCRIPTION TEXT,
            TRANSACTION_DATE TEXT NOT NULL,
            SUB_PERIOD_ID INTEGER NOT NULL,
            FOREIGN KEY (SUB_PERIOD_ID) REFERENCES SUB_PERIODS (ID) ON DELETE CASCADE
        );`,
        `CREATE TABLE IF NOT EXISTS SUB_PERIOD_SUMMARIES (
            ID INTEGER PRIMARY KEY AUTOINCREMENT,
            TOTAL_SPENT REAL NOT NULL,
            SAVINGS_DELTA REAL NOT NULL,
            SUB_PERIOD_ID INTEGER NOT NULL UNIQUE,
            FOREIGN KEY (SUB_PERIOD_ID) REFERENCES SUB_PERIODS (ID) ON DELETE CASCADE
        );`,
        `CREATE TABLE IF NOT EXISTS INCOME_PERIOD_SUMMARIES (
            ID INTEGER PRIMARY KEY AUTOINCREMENT,
            TOTAL_SPENT REAL NOT NULL,
            SAVINGS_DELTA REAL NOT NULL,
            INCOME_PERIOD_ID INTEGER NOT NULL UNIQUE,
            FOREIGN KEY (INCOME_PERIOD_ID) REFERENCES INCOME_PERIODS (ID) ON DELETE CASCADE
        );`,
    ];
    db.withTransactionSync( () => {
        // Enable foreign key support
        db.execSync('PRAGMA foreign_keys = ON;');
        // Loop through and execute each statement
        statements.forEach(statement => {
            db.execSync(statement);
        });
    })
}
/*-- Table to categorize the source of income (e.g., Salary, Freelance).
CREATE TABLE IF NOT EXISTS INCOME_CATEGORIES (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT NOT NULL,
    TYPE TEXT,
    IS_INVESTABLE INTEGER NOT NULL DEFAULT 0 -- Using INTEGER for boolean (0=false, 1=true)
);

-- The main "big period" table, linked to an income category.
CREATE TABLE IF NOT EXISTS INCOME_PERIODS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT NOT NULL,
    TOTAL_INCOME REAL NOT NULL, -- REAL is best for currency values
    BUDGETED_AMOUNT REAL,
    START_DATE TEXT NOT NULL, -- Storing dates as ISO8601 strings (YYYY-MM-DD)
    END_DATE TEXT NOT NULL,
    INCOME_CATEGORY_ID INTEGER,
    FOREIGN KEY (INCOME_CATEGORY_ID) REFERENCES INCOME_CATEGORIES (ID)
);

-- The smaller, manageable sub-periods that belong to a main income period.
CREATE TABLE IF NOT EXISTS SUB_PERIODS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT NOT NULL,
    BUDGETED_AMOUNT REAL NOT NULL,
    START_DATE TEXT NOT NULL,
    END_DATE TEXT NOT NULL,
    INCOME_PERIOD_ID INTEGER NOT NULL,
    FOREIGN KEY (INCOME_PERIOD_ID) REFERENCES INCOME_PERIODS (ID) ON DELETE CASCADE
);

-- Records every single expense, linked to a specific sub-period.
CREATE TABLE IF NOT EXISTS TRANSACTIONS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    AMOUNT REAL NOT NULL,
    DESCRIPTION TEXT,
    TRANSACTION_DATE TEXT NOT NULL,
    SUB_PERIOD_ID INTEGER NOT NULL,
    FOREIGN KEY (SUB_PERIOD_ID) REFERENCES SUB_PERIODS (ID) ON DELETE CASCADE
);

-- Summary table for sub-periods, storing pre-calculated results.
CREATE TABLE IF NOT EXISTS SUB_PERIOD_SUMMARIES (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TOTAL_SPENT REAL NOT NULL,
    SAVINGS_DELTA REAL NOT NULL,
    SUB_PERIOD_ID INTEGER NOT NULL UNIQUE,
    FOREIGN KEY (SUB_PERIOD_ID) REFERENCES SUB_PERIODS (ID) ON DELETE CASCADE
);

-- Summary table for the main income periods.
CREATE TABLE IF NOT EXISTS INCOME_PERIOD_SUMMARIES (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TOTAL_SPENT REAL NOT NULL,
    SAVINGS_DELTA REAL NOT NULL,
    INCOME_PERIOD_ID INTEGER NOT NULL UNIQUE,
    FOREIGN KEY (INCOME_PERIOD_ID) REFERENCES INCOME_PERIODS (ID) ON DELETE CASCADE
);*/
